spring.application.name=servicio-academico
server.port=8082
spring.datasource.url=jdbc:mysql://mysql:3306/colegio?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=colegio
spring.datasource.password=colegio
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

