version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_colegio
    ports:
      - "27017:27017"

  usuarios-ms:
    # Ajustado: entramos a la subcarpeta donde está el Dockerfile
    build: ./microservicios/usuarios/servicio-usuarios/servicio-usuarios
    container_name: usuarios-ms
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/db_usuarios

  academico-ms:
    # Ajustado según tu ruta de find
    build: ./microservicios/academico/servicio-academico
    container_name: academico-ms
    ports:
      - "8082:8082"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/db_academico

  asistencia-ms:
    # Ajustado según tu ruta de find
    build: ./microservicios/asistencia/servicio-asistencia
    container_name: asistencia-ms
    ports:
      - "8083:8083"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/db_asistencia

  bff:
    # Ajustado: entramos a la subcarpeta bff-colegio
    build: ./bff/bff-colegio
    container_name: bff-colegio
    ports:
      - "8080:8080"
    depends_on:
      - usuarios-ms
      - academico-ms
      - asistencia-ms