# Nombre del proyecto
spring.application.name=bff-colegio

# Puerto principal (este es el que usará el Frontend)
server.port=8080

# URLs de tus microservicios (esto le dice al BFF dónde están los otros)
url.usuarios=http://localhost:8081
url.academico=http://localhost:8082
url.asistencia=http://localhost:8083