# Nombre del proyecto
spring.application.name=bff-colegio

# Puerto principal (este es el que usará el Frontend)
server.port=8080

# Antes era localhost, ahora es el nombre del servicio en Docker
url.usuarios=http://usuarios-ms:8081
url.academico=http://academico-ms:8082
url.asistencia=http://asistencia-ms:8083